import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Next.js Product Assignment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}